routes/web.php
<?php

/*\DB::listen( function( $sql ) {
    \Log::info( $sql->sql );
    \Log::info( $sql->bindings );
    \Log::info( $sql->time );
} );*/

// Route::get( '/test', 'HomeController@test' );

Route::group(['middleware'=>'auth'],function(){
Route::group(['prefix'=>'/category/{type}','where'=>['type'=>'1|2']],function(){
	Route::get( '/', 'CategoryController@index' )->name('category.index');
	Route::get( '/create', 'CategoryController@create' )->name('category.create');
	Route::post( '/', 'CategoryController@store' )->name('category.store');
	Route::get( '/{category}/show', 'CategoryController@show' )->name('category.show');
	Route::get( '/{category}/edit', 'CategoryController@edit' )->name('category.edit');
	Route::put( '/{category}', 'CategoryController@update' )->name('category.update');
	Route::delete( '/{category}', 'CategoryController@destroy' )->name('category.destroy');
});

Route::resource( '/offer', 'OfferController' );

Route::group(['prefix'=>'/item/{type}','where'=>[ 'type'=>'1|2' ]],function() {
	Route::get( '/', 'ItemController@index' )->name('item.index');
	Route::get( '/create', 'ItemController@create' )->name('item.create');
	Route::post( '/', 'ItemController@store' )->name('item.store');
	Route::get( '/{item}/edit', 'ItemController@edit' )->name('item.edit');
	Route::put( '/{item}', 'ItemController@update' )->name('item.update');
	Route::delete( '/{item}', 'ItemController@destroy' )->name('item.destroy');
});


Route::group(['namespace'=>'RawMaterials'],function() {

Route::group(['prefix'=>'/rawrequisition'],function() {
	Route::get( '/', 'RawrequisitionController@index' )->name('rawrequisition.index');
	Route::get( '/create', 'RawrequisitionController@create' )->name('rawrequisition.create');
	Route::post( '/', 'RawrequisitionController@store' )->name('rawrequisition.store');
	Route::get( '/{rawrequisition}/show', 'RawrequisitionController@show' )->name('rawrequisition.show');
	Route::get( '/{rawrequisition}/edit', 'RawrequisitionController@edit' )->name('rawrequisition.edit');
	Route::put( '/update/{rawrequisition}', 'RawrequisitionController@update' )->name('rawrequisition.update');
	Route::post( '/approval/{rawrequisition}', 'RawrequisitionController@approve' )->name('rawrequisition.approve');
	Route::post( '/approval/{rawrequisition}', 'RawrequisitionController@reject' )->name('rawrequisition.reject');
	Route::delete( '/{rawrequisition}', 'RawrequisitionController@destroy' )->name('rawrequisition.destroy');
	Route::put( '/approve/{rawrequisition}', 'RawrequisitionController@approve' )->name('rawrequisition.approve');
	Route::put( '/reject/{rawrequisition}', 'RawrequisitionController@reject' )->name('rawrequisition.reject');
});


Route::group(['prefix'=>'/approval'],function() {
	Route::get( '/', 'ApprovalController@index' )->name('approval.index');
	Route::get( '/{rawrequisition}/show', 'ApprovalController@show' )->name('approval.show');
	Route::put( '/purchase/{rawrequisition}', 'ApprovalController@purchase' )->name('approval.purchase');
});


Route::group(['prefix'=>'/purchase'],function() {
	Route::get( '/', 'PurchaseController@index' )->name('purchase.index');
	Route::get( '/{rawrequisition}/show', 'PurchaseController@show' )->name('purchase.show');
	Route::put( '/purchase/{rawrequisition}', 'PurchaseController@receive' )->name('purchase.receive');
});


Route::group(['prefix'=>'/receive'],function() {
	Route::get( '/', 'ReceiveController@index' )->name('receive.index');
	Route::get( '/{rawrequisition}/show', 'ReceiveController@show' )->name('receive.show');
});

});


Route::group(['namespace'=>'FinishedGoods'],function() {

Route::group(['prefix'=>'/finrequisition'],function() {
	Route::get( '/', 'FinrequisitionController@index' )->name('finrequisition.index');
	Route::get( '/create', 'FinrequisitionController@create' )->name('finrequisition.create');
	Route::post( '/', 'FinrequisitionController@store' )->name('finrequisition.store');
	Route::get( '/{finrequisition}/show', 'FinrequisitionController@show' )->name('finrequisition.show');
	Route::get( '/{finrequisition}/edit', 'FinrequisitionController@edit' )->name('finrequisition.edit');
	Route::put( '/update/{finrequisition}', 'FinrequisitionController@update' )->name('finrequisition.update');
	Route::post( '/approval/{finrequisition}', 'FinrequisitionController@approve' )->name('finrequisition.approve');
	Route::post( '/approval/{finrequisition}', 'FinrequisitionController@reject' )->name('finrequisition.reject');
	Route::delete( '/{finrequisition}', 'FinrequisitionController@destroy' )->name('finrequisition.destroy');
	Route::put( '/approve/{finrequisition}', 'FinrequisitionController@approve' )->name('finrequisition.approve');
	Route::put( '/reject/{finrequisition}', 'FinrequisitionController@reject' )->name('finrequisition.reject');
});

Route::group(['prefix'=>'/finapproval'],function() {
	Route::get( '/', 'FinapprovalController@index' )->name('finapproval.index');
	Route::get( '/{finrequisition}/show', 'FinapprovalController@show' )->name('finapproval.show');
	Route::post( '/{finrequisition}/send', 'FinapprovalController@send' )->name('finapproval.send');
});

Route::group(['prefix'=>'/storeapproval'],function() {
	Route::get( '/', 'StoreapprovalController@index' )->name('storeapproval.index');
	Route::get( '/{finrequisition}/show', 'StoreapprovalController@show' )->name('storeapproval.show');
	Route::put( '/finpurchase/{finrequisition}', 'StoreapprovalController@receive' )->name('storeapproval.receive');
});


Route::group(['prefix'=>'/fgreceive'],function() {
	Route::get( '/', 'FgreceiveController@index' )->name('fgreceive.index');
	Route::get( '/{finrequisition}/show', 'FgreceiveController@show' )->name('fgreceive.show');
	Route::get( '/purchase/{finrequisition}', 'FgreceiveController@purchase' )->name('fgreceive.purchase');
});

});

//end


Route::resource( '/unit', 'UnitController' );

Route::resource( '/floor', 'FloorController' );

Route::resource( '/room', 'RoomController' );

Route::resource( '/table', 'TableController' );

Route::resource( '/cusorder', 'CusOrderController' );
Route::get( '/cusorder-item-id', 'CusOrderController@getPrice' )->name('cusordergetPrice');

Route::resource( '/formula', 'FormulaController' );

Route::resource( '/supplier', 'SupplierController' );



Route::get('/', function () {
    return view('welcome');
});
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/website', 'SiteController@index')->name('website');

Route::get( '/menu/{category_id}', 'MenuController@show' )->name('menu.show');

app/Formula.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Formula extends Model
{

    protected $table = 'formulas';

    protected $fillable = [
         'item_id'
    ];

    // protected $hidden = [];

    public function formula_item()
    {
        return $this->hasmany( 'App\FormulaItem' );
    }

    public function fin_item()
    {
    	return $this->belongsTo( 'App\Item', 'item_id', 'id' );
    }

}

app/Http/Controllers/FormulaController.php
<?php

namespace App\Http\Controllers;

use App\Formula;
use App\FormulaItem;
use App\Item;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

class FormulaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       //$formulas = Formula::with('formula_item.raw_items')->latest()->get();
       // dd(Formula::find(1)->load('fin_item'));
       $items = Item::with('formula.fin_item')->where('item_type', '2')->get();
       $formulas = Formula::with('formula_item','fin_item')->get();//dd($items);
       // return view( 'formula.index' )->with( ['items'=> $items, 'formulas'=> $formulas] );
       return view( 'formula.index' )->with( ['items'=> $items,'formulas'=> $formulas] );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       $ingredients = Item::latest()->get()->where('item_type', '1');
       $items = Item::latest()->get()->where('item_type', '2');
       return view( 'formula.create' )->with( ['ingredients'=> $ingredients , 'items'=> $items] );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    // $input=$this->validate($request,[
    //     'item_id' => 'required'
    // ]);
   // dd($request->all());
    $input = $request->input('formulas');

    $input_formula_items = $request->input('formulas_item');

    $formula = Formula::create($input);
    $formula->formula_item()->createMany($input_formula_items);
    // dd($formula);
    return redirect()->route('formula.index');
    }

    /**
     * Display the specified resource.category
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Formula $formula)
    {
        $formula->load('formula_item.raw_items','fin_item');//lazy load
        return view('formula.view',['formula'=>$formula]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Formula $formula)
    {
        $ingredients = Item::latest()->get()->where('item_type', '1');
        $items = Item::latest()->get()->where('item_type', '2');
        $formula->load('formula_item','fin_item');
        return view('formula.edit',[ 'ingredients'=>$ingredients,'items'=>$items, 'formula'=>$formula ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Formula $formula)
    {
        //dd($request);
        //$formula->formula_item()->delete();
        //$formula->formula_item()->createMany( $request->input( 'formulas_item' ) );
        //return redirect()->route('formula.index');
        $formula->formula_item()->delete();
        $formula->formula_item()->createMany( $request->input( 'formulas_item' ) );
        return redirect()->route('formula.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Formula $formula)
    {
        $formula->formula_item()->delete();
        $formula->delete();
        return redirect()->route('formula.index');
    }
}

resources/views/formula/create.blade.php
@extends('adminlte::page')

@section('title', 'Test')

@section('content_header')
  <h1>Formula Items</h1>
@stop

@section('content')

<form class="well" action="{{ route('formula.store') }}" method="post">
	{{ csrf_field() }}

    <fieldset>

	   {{--  <h3>Formula Items</h3> --}}

      <div class="form-group row">
        <label class="col-md-2">Item Name</label>
          <div class="col-md-4">
                <select style="width:250px;" class="input-group form-control" id="item_id" name="formulas[item_id]" required>
                  <option value="" selected>Select One</option>
                  @foreach($items as $item)
                  <option value="{{$item->id}}">{{$item->item_name}}</option>
                  @endforeach
              </select>
          </div>
      </div>

      <div class="form-group row">

        <div class="form-group row">
        	<div class="col-md-4">
  				<button type="button" class="btn btn-primary ingredient-add">+</button>
        	</div>
     	</div>

	    <table class="table table-sm">
	    	<thead>
	    		<tr>
	    			<td>#</td>
	    			<td>Item Name</td>
	    			<td>Amount</td>
	    		</tr>
	    	</thead>
	    	<tbody class="ingredients"></tbody>
	    </table>

     	<div class="form-group">
      		<center>
      			<button name="create" style=" margin-top: 10px; padding-left: 80px; padding-right: 80px;" class="btn btn-success">Submit</button>
        		{{-- <a href="" style=" margin-top: 10px; padding-left: 80px; padding-right: 80px;" class="btn btn-primary">Back</a> --}}
      		</center>
     	</div>

  	</fieldset>
</form>
@stop

{{-- @section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop --}}

@section('js')
<script>
	$( document ).ready( function() {
      var i = 0;

		$( document ).on( 'click', '.ingredient-remove', function() {
	        $( this ).parent().parent().remove();
	    } );

		$( '.ingredient-add' ).click( function() {
			$( '.ingredients' ).append( '<tr class="ingredient">\
    			<td>\
    				<button type="button" class="btn btn-sm btn-danger ingredient-remove">-</button>\
    			</td>\
    			<td>\
    				<select style="width:250px;" class="input-group form-control" name="formulas_item['+i+'][item_id]" required>\
                  <option value="" selected>Select One</option>\
                  @foreach($ingredients as $ingredient)\
                  <option value="{{$ingredient->id}}">{{$ingredient->item_name}}</option>\
                  @endforeach\
              </select>\
    			</td>\
    			<td>\
    				<input type="text" name="formulas_item['+i+'][amount]" placeholder="Amount" class="form-control" required/>\
    			</td>\
    		</tr>' );
      i++;
		} );

	} );
</script>
@stop

resources/views/formula/edit.blade.php
@extends('adminlte::page')

@section('title', 'Test')

@section('content_header')
  <h1>Formula Items</h1>
@stop

@section('content')

<form class="well" action="{{ route('formula.update', $formula->id) }}" method="post">
@csrf
@method("put")

    <fieldset>

	   {{--  <h3>Formula Items</h3> --}}

      <div class="form-group row">
        <label class="col-md-2">Item Name</label>
          <div class="col-md-4">
                <select style="width:250px;" class="input-group form-control" id="item_id" name="formulas[item_id]" required>
                  <option value="" selected>Select One</option>
                  @foreach($items as $item)
                  <option value="{{$item->id}}" @if($item->id==$formula->item_id) selected @endif>{{$item->item_name}}</option>
                  @endforeach
              </select>
          </div>
      </div>

      <div class="form-group row">

        <div class="form-group row">
        	<div class="col-md-4">
  				<button type="button" class="btn btn-primary ingredient-add">+</button>
        	</div>
     	</div>

	    <table class="table table-sm">
	    	<thead>
	    		<tr>
	    			<td>#</td>
	    			<td>Item Name</td>
	    			<td>Amount</td>
	    		</tr>
	    	</thead>

        <tbody class="ingredients">
          @foreach( $formula->formula_item as $i => $formula_item )
            <tr class="ingredient">
              <td>
                <button type="button" class="btn btn-sm btn-danger ingredient-remove">-</button>
              </td>
              <td>
                <select style="width:250px;" class="input-group form-control" name="formulas_item[{{$i}}][item_id]" required>
                      @foreach($ingredients as $ingredient)
                        <option value="{{$ingredient->id}}" @if($ingredient->id==$formula_item->item_id) selected @endif>
                          {{$ingredient->item_name}}
                        </option>
                      @endforeach
                  </select>
              </td>
              <td>
                <input type="text" id="amount" name="formulas_item[{{$i}}][amount]" placeholder="Amount" class="form-control" value="{{ $formula_item->amount }}" required/>
              </td>
            </tr>
          @endforeach
        </tbody>
	    </table>

     	<div class="form-group">
      		<center>
      			<button name="create" style=" margin-top: 10px; padding-left: 80px; padding-right: 80px;" class="btn btn-success">Submit</button>
        		{{-- <a href="" style=" margin-top: 10px; padding-left: 80px; padding-right: 80px;" class="btn btn-primary">Back</a> --}}
      		</center>
     	</div>

  	</fieldset>
</form>
@stop

{{-- @section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop --}}

@section('js')
<script>
	$( document ).ready( function() {
      var i = 0;

		$( document ).on( 'click', '.ingredient-remove', function() {
	        $( this ).parent().parent().remove();
	    } );

		$( '.ingredient-add' ).click( function() {
			$( '.ingredients' ).append( '<tr class="ingredient">\
    			<td>\
    				<button type="button" class="btn btn-sm btn-danger ingredient-remove">-</button>\
    			</td>\
    			<td>\
    				<select style="width:250px;" class="input-group form-control" name="formulas_item['+i+'][item_id]" required>\
                  <option value="" selected>Select One</option>\
                  @foreach($ingredients as $ingredient)\
                  <option value="{{$ingredient->id}}"@if($ingredient->id==$formula->item_id) selected @endif>{{$ingredient->item_name}}</option>\
                  @endforeach\
              </select>\
    			</td>\
    			<td>\
    				<input type="text" name="formulas_item['+i+'][amount]" placeholder="Amount" class="form-control" required/>\
    			</td>\
    		</tr>' );
      i++;
		} );

	} );
</script>
@stop

resources/views/formula/index.blade.php
@extends('adminlte::page')

@section('title', 'Test')

@section('content_header')
    {{-- <h1>Formula Items</h1> --}}
@stop

@section('content')
<div class="well">
	 <a href="{{ route('formula.create') }}" class="btn btn-success">Create</a>

    <fieldset>

	    <h3>Formula Items</h3>

	    <table class="table table-sm">
	    	<thead>
	    		<tr>
	    			<td>#</td>
	    			<td>Item name</td>
	    			<td>Total Ingredients</td>
	    			<td>Action</td>
	    		</tr>
	    	</thead>
	    	@foreach( $formulas as $formula )
	    	<tbody>
	    		<?php $i=0; ?>
	    		<td><?php echo ++$i; ?></td>
		        <td>{{ $formula->fin_item->item_name }}</td>
	    		<td></td>
	    		<td>
	    			<a href="{{ route('formula.show', $formula->id) }}" class="btn btn-info">View</a>
		              <a href="{{ route('formula.edit', $formula->id) }}" class="btn btn-warning">Edit</a>
		              <form action="{{ route('formula.destroy', $formula->id) }}" method="post" style="display:inline-block;">
				          @csrf
				          @method('delete')
				          <button type="submit" class="btn btn-danger" onclick="if(confirm('Are you sure?')==0){return false;}">Delete</button>
		              </form>
		        </td>
	    	</tbody>
	    	@endforeach
	    </table>

  	</fieldset>
</div>
@stop

resources/views/formula/view.blade.php
@extends('adminlte::page')

@section('title', 'Test')

@section('content_header')
  <h1>Formula Items</h1>
@stop

@section('content')

    <fieldset>

	   {{--  <h3>Formula Items</h3> --}}

      <div class="form-group row">
        <label class="col-md-2">Item Name</label>
          <div class="col-md-4">
                <select style="width:250px;" class="input-group form-control" id="item_id" name="formulas[item_id]" required>
                  <option value="" selected>Select One</option>
                  {{-- @foreach($items as $item)
                  <option value="{{$item->id}}">{{$item->item_name}}</option>
                  @endforeach --}}
              </select>
          </div>
      </div>

      <div class="form-group row">

        <div class="form-group row">
        	<div class="col-md-4">
  				<button type="button" class="btn btn-primary ingredient-add">+</button>
        	</div>
     	</div>

	    <table class="table table-sm">
	    	<thead>
	    		<tr>
	    			<td>#</td>
	    			<td>Item Name</td>
	    			<td>Amount</td>
	    		</tr>
	    	</thead>
	    	<tbody class="ingredients"></tbody>
	    </table>

     	<div class="form-group">
      		<center>
      			<button name="create" style=" margin-top: 10px; padding-left: 80px; padding-right: 80px;" class="btn btn-success">Submit</button>
        		{{-- <a href="" style=" margin-top: 10px; padding-left: 80px; padding-right: 80px;" class="btn btn-primary">Back</a> --}}
      		</center>
     	</div>

  	</fieldset>

@stop

{{-- @section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop --}}

@section('js')
<script>
	$( document ).ready( function() {
      var i = 0;

		$( document ).on( 'click', '.ingredient-remove', function() {
	        $( this ).parent().parent().remove();
	    } );

		$( '.ingredient-add' ).click( function() {
			$( '.ingredients' ).append( '<tr class="ingredient">\
    			<td>\
    				<button type="button" class="btn btn-sm btn-danger ingredient-remove">-</button>\
    			</td>\
    			<td>\
    				<select style="width:250px;" class="input-group form-control" name="formulas_item['+i+'][item_id]" required>\
                  <option value="" selected>Select One</option>\
   </select>\
    			</td>\
    			<td>\
    				<input type="text" name="formulas_item['+i+'][amount]" placeholder="Amount" class="form-control" required/>\
    			</td>\
    		</tr>' );
      i++;
		} );

	} );
</script>
@stop